### ISSUE TITLE
BUG: Intellij 2016.2 - Suggests re-enabling it's plugin

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-intellij#1008]
1. Our intellij plugin suggests disabling the Intellij GAE plugin.
2. disable it.
3. import a GAE Project.
4. Intellij suggests enabling the facet

Chaos ensues.

**Comment by patflynn** [comment]
Could you provide more details about the 'chaos'?  Your sequence of steps
is expected behavior since our plugin includes an App Engine facet for
standard.

**Comment by lesv** [comment]
The facet that it suggested enabling mentioned GWT and more.

**Comment by lesv** [comment]
![screen shot 2016-10-12 at 3 00 53 pm](https://cloud.githubusercontent.com/assets/1136014/19329294/cb1ad3b4-908c-11e6-9dea-74311a599dd6.png)

**Comment by patflynn** [comment]
You don't appear to have disabled the Google app engine integration plugin.

On Oct 12, 2016 6:02 PM, "Les Vogel" <notifications@github.com> wrote:

[image: screen shot 2016-10-12 at 3 00 53 pm]
<https://cloud.githubusercontent.com/assets/1136014/19329294/cb1ad3b4-908c-11e6-9dea-74311a599dd6.png>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1008#issuecomment-253352903>,
or mute the thread

**Comment by lesv** [comment]
That was the result of clicking on enable link, if I hadn't cut it off, you would have seen the apply button present.  (I just checked my existing settings)

**Comment by patflynn** [comment]
Could you verify that the Google Cloud Tools plugin is installed and enabled?  I'm wondering if somehow it's missing which is why it's suggesting you install the old one.

**Comment by lesv** [comment]
Definitely is.
![screen shot 2016-10-13 at 10 42 30 am](https://cloud.githubusercontent.com/assets/1136014/19360075/d019c118-9131-11e6-9a5c-96a6dfe9bec6.png)

**Comment by etanshaul** [comment]
obsolete
