### ISSUE TITLE
Cannot upload source to a Google Cloud Repository

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/google-cloud-intellij#1011]
Observed bug on Linux, IDEA 2016.2.1

Steps to reproduce:
1. Create a new project. Navigate to VSC > Import into Version Control > Upload Project to Google Cloud...
2. Select a cloud project and click OK.
3. Observe error dialog:

![screenshot from 2016-10-12 16 56 28](https://cloud.githubusercontent.com/assets/1039411/19327403/db662cae-909c-11e6-9c84-e5c7354e05ec.png)

Associated error message from logs:

```
2016-10-12 16:41:04,399 [1788017]   INFO -  #git4idea.commands.GitHandler - java.io.IOException: Authentication failed: 
2016-10-12 16:41:04,399 [1788017]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.authenticate(SSHMain.java:298) 
2016-10-12 16:41:04,399 [1788017]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.start(SSHMain.java:172) 
2016-10-12 16:41:04,399 [1788017]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.ssh.SSHMain.main(SSHMain.java:137) 
2016-10-12 16:41:04,405 [1788023]   INFO -  #git4idea.commands.GitHandler - fatal: Could not read from remote repository. 
2016-10-12 16:41:04,405 [1788023]   INFO -  #git4idea.commands.GitHandler - Please make sure you have the correct access rights 
2016-10-12 16:41:04,405 [1788023]   INFO -  #git4idea.commands.GitHandler - and the repository exists. 
```

**Comment by patflynn** [comment]
I've seen another bug in the same workflow importing on Windows.

It's odd because checkout worked fine, and import worked for me on Linux.

Worth investigating this.

**Comment by etanshaul** [comment]
Summary of whats going on here:

Our plugin registers a GitHttpAuthDataProvider, to manage authentication for Git interactions:

```
  <extensions defaultExtensionNs="Git4Idea">
    <GitHttpAuthDataProvider implementation="com.google.cloud.tools.intellij.vcs.GcpHttpAuthDataProvider" />
  </extensions>
```

The Git4Idea integration also includes a default auth provider that is always created. As a result, there will always be multiple data provider extensions registered (and the order when retrieving these extensions is not guaranteed). This default auth provider stores the credentials using the IJ password manager (which by default will defer to the system keychain).

The intellij git integration code, in order to determine which of the registered auth providers to use, loops through the available ones and checks to see if the returned auth by the given provider is populated (e.g. password is not null).

In a "normal" workflow, where the user never provided credentials to the default auth provider, the default auth provider will be skipped, and the custom `GcpHttpAuthDataProvider` will be used and everything will work.

However, if the user is using the a [Git Credential Manager](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) (there is an implementation for multiple OSs), then any interaction with Git that requires credentials is hijacked an a credential prompt is shown:

![image](https://cloud.githubusercontent.com/assets/1735744/22348578/35990e68-e3da-11e6-9b8b-aa38b1bed77b.png)

Upon saving these credentials, when the default auth manager is queried (as described above), it will then return populated credentials and hence _never invoke the custom GCP auth provider_.

**Comment by etanshaul** [comment]
Update: I was able to fix the problem by explicitly clearing out any stored credentials for the GCP url from the password manager prior to performing a Git operation. This has the effect of forcing the Git integration to use our custom auth provider.

Still checking to see if this is the best approach.

**Comment by etanshaul** [comment]
closing. dup of #1174
