### ISSUE TITLE
Default deploy run configuration created after new AE project wizard causes error when run

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1114]
1) File -> New project
2) Java EE -> Web -> App Engine Standard
3) Click run on the Google App Engine Deployment run config
4) observe error notification "Error running Google App Engine Deployment: Server: App Engine not found'
4.1) This also happened because the deployment source was not selected

Expected results:
Ideally there would be an indication on the run config icon that it's not quite ready to go, or clicking run would open up the run config so the user can specify the missing paramter.

Also if there is one valid deployment source available ideally it would be selected by default.

**Comment by nkibler** [comment]
I can't seem to find the corresponding form class for this deployment config, any ideas? Screenshot below:

<img width="1070" alt="screen shot 2017-08-01 at 1 47 17 pm" src="https://user-images.githubusercontent.com/14352762/28838970-105534a0-76c0-11e7-9567-ab6ab0e81282.png">

**Comment by etanshaul** [comment]
The server / deployment part?

Thats internal to the IJ platform, not controlled by us. They have an extension point to add a extra which is what we use to add all of our AE stuff.

**Comment by nkibler** [comment]
Ah so for these `Google App Engine Deployment` configs, where is the code on our side for it? I found the standard local server stuff (`AppEngineServerConfigurationType`) but can't find the deployment config.

**Comment by etanshaul** [comment]
`AppEngine[Flexible|Standard]DeploymentEditor` and the form files of the same name are the editors.

`AppEngineDeploymentConfiguration` is the config.

But I suspect this is not what you are after?

**Comment by etanshaul** [comment]
One of the problems that I see here is that in that initial state of the dialog as shown in your screenshot, no fields are in error. This means there is no chance for the `checkConfiguration` method to get called to mark the run config as in error.

Furthermore, since all of that is platform code (prior to selecting anything specific to our plugin), I suspect there isn't anything we can do on our end (at least for the specific reproduction steps outline by @patflynn) to have the run config marked as not being ready. 

Similarly, clicking 'run' to deploy in this state will not run our plugin code (since no server was selected yet), so I also doubt there is anything we can do to capture this in the deployment flow.

**Comment by etanshaul** [comment]
Check out `DeployToServerRunConfiguration`. Specifically the `getState` method where that error indicated by the bug comes from ("Server is not specified"). Also, look at `checkConfiguration` where no `RuntimeConfigurationError` is thrown for a missing server or deployment source.

**Comment by nkibler** [comment]
Yeah I don't think there's anything we can do about this; it's all platform code as you mentioned. @patflynn WDYT?

**Comment by patflynn** [comment]
closing. We got bigger fish to fry.
