### ISSUE TITLE
App Engine Deployment run configuration UI is sluggish 

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/google-cloud-intellij#1127]
There appears to be a long-running process that's blocking the UI thread.

**Comment by patflynn** [comment]
Is this a new issue? How often does it happen?

**Comment by aslo** [comment]
I have a feeling it's due to some of the new validations we introduced recently. It appears to happen as you manually type in any of the text fields on the deployment run config editor - it feels very sluggish.

**Comment by patflynn** [comment]
are we executing validation for each keypress in the field?

**Comment by etanshaul** [comment]
noting some findings:

- the issue does not seem to be dependent on a version of IJ
  - I can reproduce it in both 15 and 2016
- so far, I can only reproduce it when running IJ by building our plugin from the sources
- I can reproduce it regardless of if it is in run / debug mode

**Comment by etanshaul** [comment]
@aslo and I got to the bottom of this:

The problem is the cloud sdk validation is slow. This validation is currently happening synchronously in the UI thread causing the config panel to be sluggish.

There is another issue we uncovered: the Cloud SDK panel is performing the app engine java components check when it shouldn't be. Not all uses of the SDK require this component. This bug was surfaced when the validation logic in the common lib was refactored.
