### ISSUE TITLE
Do not perform Cloud SDK validations on the UI thread

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/google-cloud-intellij#1161]
The AppEngineDeploymentRunConfigurationEditor performs form validation from the UI thread. This is not ideal since validating the Cloud SDK now involves file IO. 

Investigate ways to perform this validation asynchronously.  See `DialogWrapper.getValidationThreadToUse()`. Is it possible to configure something similar for a run config editor?

**Comment by nkibler** [comment]
I don't think this validation can be done in the background because we would lose the ability to throw a `ConfigurationException` when `applyEditorTo()` is called on our editors. We also don't manage the deploy buttons in the window (AFAIK) so we don't have the opportunity to show a spinner, for example, while we kick off the validation behind the scenes, and only continue thereafter if it's valid.

FWIW, `DialogWrapper.getValidationThreadToUse()` returns the UI thread: https://upsource.jetbrains.com/idea-ce/file/idea-ce-d00d8b4ae3ed33097972b8a4286b336bf4ffcfab/platform/platform-api/src/com/intellij/openapi/ui/DialogWrapper.java?nav=12122:12160:focused&line=510

@patflynn @etanshaul, what do you think?

**Comment by etanshaul** [comment]
I'm not sure if it addresses this particular issue, but just want to point out that one thing that we should do soon (I should open an issue for this) is to stop throwing configuration exceptions so that the user can still save the dialog in an incomplete state.

**Comment by nkibler** [comment]
Oh if that's the case, then it's definitely easier to do. It might make sense, then, to move validation like this to deployment time. We could fail deployment if the `app.yaml` is invalid, for example. WDYT?

**Comment by etanshaul** [comment]
Instead of moving these errors to deployment time, there is a mechanism to have the run configs "know" that they are an invalid statue - this is usually indicated by a little error icon overlaid on top of the run config.

Then, when trying to run it, it doesn't execute but opens up the dialog for more editing.

**Comment by etanshaul** [comment]
besides, we do already have deployment time checks in place for things like invalid app.yaml

**Comment by nkibler** [comment]
Sounds good, I'll follow up on this after #1407 is fixed.

**Comment by nkibler** [comment]
I think this is now obsolete. As part of fixing #1407, we changed the configuration to override `checkConfiguration()` and throw exceptions from that instead of during the `applyEditorTo()` method, as recommended. The calling of this method is still handled by the framework, so it will choose what thread to use. It may be the case now that they are using a background thread to validate the config, but this isn't our problem anymore.
