### ISSUE TITLE
Don't force web 2.5 for Java 8 runtime apps

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1231]

**Comment by etanshaul** [comment]
see https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1205 for some ideas of what needs to be done

**Comment by etanshaul** [comment]
This issue should also handle detection of the java runtime version and servlet version and warn when there are mismatches

**Comment by patflynn** [comment]
this is fixed right? @etanshaul

**Comment by etanshaul** [comment]
I'm not really sure what this issue was meant to track.

What we have already done is update the generated web.xml via the AE standard project wizard to use servlet version 2.5 (#1205).

What we need to do is add inspections to web.xml and appengine-web.xml for servlet version & runtime mismatch, perhaps with quickfixes (#1193).

I think we can close this one and just use #1205 to track the remaining todos.

**Comment by etanshaul** [comment]
will close. feel free to reopen if you think its still needed.
