### ISSUE TITLE
Swap App Engine Standard local development server to devappserverV1

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1345]

**Comment by sparhomenko** [comment]
@patflynn Can you provide some background for the change? It seems this change is part of the 17.2.4_2017 version released yesterday, and it breaks our development environment as we have some DevAppServerV2-specific configuration changes. We can revert back to DevAppServerV1, but this would break our tests since latest release of `com.google.cloud.tools:appengine-maven-plugin` doesn't seem to support DevAppServerV1. It would be nice to understand which DevAppServer version is now recommended for GAE Standard apps, and when it would be possible to use the same version in IntelliJ and Maven plugins.

**Comment by loosebazooka** [comment]
@sparhomenko, the maven plugin will see a release today.

**Comment by sparhomenko** [comment]
@loosebazooka We tried 1.3.0-rc1 today and with some environment variables issues were able to switch to DevAppServerV1. Thanks.

**Comment by loosebazooka** [comment]
Any chance you can share your environment variable issues, so we can hopefully address them. Maybe start a new issue here : https://github.com/GoogleCloudPlatform/app-maven-plugin

**Comment by loosebazooka** [comment]
As for background. Dev App Server 2 support for Java was not where we wanted it to be for our tools (intellij/eclipse/gradle/maven), it's better for python and go. So we've moved back to Dev App Server 1 to give users a better experience while Dev App Server 2's Java support is improved.

**Comment by sparhomenko** [comment]
Thanks for the explanation @loosebazooka. The environment variable issue I mentioned is more related to the IntelliJ IDEA plugin, so I raised it here in #1364.
