### ISSUE TITLE
Cannot apply changes in Settings dialog if there is a problem with the Cloud SDK configuration

### ISSUE THREAD

**Issue by chashnikov** [GoogleCloudPlatform/google-cloud-intellij#1408]
The same thing as with [run configurations](https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1407): I cannot apply changes and close the Settings dialog if there is a problem with the Cloud SDK in Build, Execution, Deployment | Clouds. It's very inconvenient because I may have changes in other parts of Settings dialog and I'll lose them if I press 'Cancel'.

**Comment by chashnikov** [comment]
In order to fix this you need to avoid throwing exceptions from com.google.cloud.tools.intellij.appengine.cloud.AppEngineCloudConfigurable#apply. The error will be shown in UI anyway, and you may also show it if a user tries to deploy to a misconfigured cloud, but don't forbid to apply changes in the Settings dialog.

**Comment by patflynn** [comment]
@nkibler can you update this bug?  I thought you had some PRs that addressed this.

**Comment by nkibler** [comment]
This is slightly different. It's the same problem reported in #1407 but it's for the Google App Engine Cloud settings as shown below:

<img width="1168" alt="screen shot 2017-08-01 at 11 10 18 am" src="https://user-images.githubusercontent.com/14352762/28832339-277609d6-76aa-11e7-8aa9-b665c2aa1608.png">

**Comment by nkibler** [comment]
So we don't have the same opportunity to follow the pattern we applied to the run configuration. Specifically, these configurations are fundamentally different, right down to the SDK level.

The run configuration we changed in #1407 provided a construct to check the configuration for validity and IDEA took care of the rest (calling it, showing the red X, opening the config when it's still invalid and pressing the run button, etc.).

This, however, extends from `UnnamedConfigurable`, which does not provide a similar construct: https://upsource.jetbrains.com/idea-ce/file/idea-ce-d00d8b4ae3ed33097972b8a4286b336bf4ffcfab/platform/platform-api/src/com/intellij/openapi/options/UnnamedConfigurable.java

We have two options:

1. Leave it as-is and the user cannot save the cloud configurable until they satisfy the validation requirements (non-empty Cloud SDK directory).
2. Remove the validation entirely and let it fail on runtime.

In this instance, I'm favoring (1) because it's nice to see where the problem is (2 would not show this) and this form is much shorter than the run configuration. @patflynn @etanshaul WDYT? Maybe we go for (1) now and could re-evaluate if the form becomes larger.

**Comment by etanshaul** [comment]
check out the sdk panel as seen from within the google settings:
project settings -> other settings (or "google" directly depending on if you have other settings here) -> google -> cloud SDK

Notice how it lets you save the form even with an invalid SDK, and it still shows error messages underneath the field.

These decisions were deliberate: in the IDE-wide google settings it doesn't make sense to force the SDK because the user may not need it. However for the "Clouds", there's pretty much nothing you can do without it. But since we did get push-back from the JB guys about doing this, can't we just do something similar to the Google settings panel?

**Comment by etanshaul** [comment]
In other words, why not (2) but without removing validation entirely? I.e. we still have field level validation messages, but we don't prevent saving the panel.

**Comment by nkibler** [comment]
Oh true, I was under the impression that the `AppEngineCloudConfigurable` was performing the field validation but on second look, the `CloudSdkPanel` handles it. This is a simple change, then, because we just have to make the `AppEngineCloudConfigurable` mimic the `CloudSdkConfigurable`. I'll send a PR shortly.
