### ISSUE TITLE
In the project selectors, cannot select a different project after making a selection without clearing the text first

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/google-cloud-intellij#1729]
When using the project selector in gcs, I accidentally picked the wrong project. When I tried to correct this, I could not get the list of projects to display. I hit the refresh button, but I am not given the option of picking a new project.

**Comment by etanshaul** [comment]
how were you trying to correct the project? by typing or by selecting it from the dropdown? do both not work?

**Comment by etanshaul** [comment]
also just to make sure:

if you already have something typed into the project selector, then you won't see other projects (unless the filter matches what you have typed)

try deleting the text first and see if the projects show up again. This may be UX thing we can discuss too.

**Comment by parkjam4** [comment]
Through the drop down. Didn't even realize that you could type the project name.

**Comment by etanshaul** [comment]
To summarize:

This is a UX thing: you _can_ still select a different project if you clear out the text. This is because what is displayed in the tree is filtered based on the text in the field.

We could probably do better here by having some "clear filter" button or something like that to avoid this confusion. 

I updated the title too to make it clearer.
