### ISSUE TITLE
EAP build failure

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1840]
https://sponge.corp.google.com/target?id=d9d43ee7-8b3d-4f32-a5b9-11ba90f34667&target=google-cloud-intellij/gcp_ubuntu/eap/continuous&searchFor

**Comment by etanshaul** [comment]
@ivanporty mind looking into this?

**Comment by ivanporty** [comment]
There are two breaking changes in EAP:

1. Darcula UI change, here is the changelist:
https://github.com/JetBrains/intellij-community/commit/bb3bf5dad5db86d1f0ca540c3609631b86bd9099
I think they reverted but EAP is still broken.

2. Errorprone fail with `Hyperlink` class making `getText()` public and needed `@Override`.

In order to make it work we will have to switch to 2017.3 I guess.

**Comment by etanshaul** [comment]
so then we don't have anything to do here then (since they will probably release a new EAP with the fix)?

**Comment by ivanporty** [comment]
Yes, we cannot fix this without they fixing (1). If they fix (1), we can rename the method for (2) to avoid breaking things with @Override.

**Comment by etanshaul** [comment]
It seams that the previous error (metioned in the description of this PR) is no longer a problem.

Instead the EAP is failing for different reasons:
https://sponge.corp.google.com/target?id=b45e48a8-a57b-45c1-a206-d6e084df3867&target=google-cloud-intellij/gcp_ubuntu/eap/continuous&searchFor=&show=ALL&sortBy=STATUS

essentially due to `java.lang.IllegalStateException: Test project is not disposed: Project ` errors

Will continue to use this same issue to track this.

**Comment by etanshaul** [comment]
eap is passing now. could have been flakiness, but closing this for now.
