### ISSUE TITLE
Show time in milliseconds for google clould intellij plugin debugger java

### ISSUE THREAD

**Issue by danialfaridsada** [GoogleCloudPlatform/google-cloud-intellij#1914]
For the intellij google cloud debugger when the snapshot is captured it shows only the time of capture in minutes. Could you make the change to show the time with more precision in milliseconds? That would be very helpful to find out where the system slows down or how long it takes to execute a method or an operation.

Thanks

**Comment by etanshaul** [comment]
@danialfaridsada thanks for the suggestion. We'll look into improving this.

**Comment by etanshaul** [comment]
@danialfaridsada got a chance to look into this. quick question: which time stamp are you referring to that is being show in seconds? Currently its showing the time with minute precision as far as I can see:
![image](https://user-images.githubusercontent.com/1735744/36436452-459a12c2-1632-11e8-921b-6be4d7017f12.png)

I could be missing something, but I just want to make sure we are referring to the same thing.

**Comment by danialfaridsada** [comment]
Yes you are right, I meant to say minutes. It is shows in minutes and those are the exact places I was referring to. I edited to description of the first post.

**Comment by etanshaul** [comment]
Hi @danialfaridsada. I followed up with the stackdriver debugger team and turns out that using the snapshot timestamp isn't advisable for your use-case:

The timestampe itself is taken on the server and happens after the snapshot is sent by the agent (and after processing by the server etc.). Therefore its not advisable as a way to measure execution time as you describe.

That being said, you can take a look at [Debug Logpoints](https://cloud.google.com/debugger/docs/using/logpoints) which gives you a way to inject log statements into your code, and will give you millisecond resolution. As described on the page, you can inject these log statements using gcloud (or via the cloud console). e.g:

`gcloud debug logpoints create [LOCATION] [MESSAGE]`

closing this issue, but feel free to follow up if you have any more questions

**Comment by danialfaridsada** [comment]
@etanshaul How do I get the millisecond time in the `Logpoint`? If I use {System.currentTimeMillis()} I get this error: `Calling java.lang.System.currentTimeMillis is not allowed`.

**Comment by danialfaridsada** [comment]
Oh you mean the timestamp on that log entry is accurate to show the exact time the logpoint has reached?

**Comment by etanshaul** [comment]
yes exactly, I was just about to write that. You can view the logs from the cloud console and use the timestamp on the log entry, like you said.
