### ISSUE TITLE
previous major versoin (2017) CI build is red

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#2031]

**Comment by etanshaul** [comment]
this is the error we are getting (test only):
![image](https://user-images.githubusercontent.com/1735744/39144511-fc42de1c-46fe-11e8-9924-e491953030a3.png)

**Comment by etanshaul** [comment]
so that GCS test failure is a red herring:

the test failure occurs in _any_ test that calls (directly or indirectly) `UsageTrackerProvider.getInstance()`. And the underlying issue is a thread leak:

![image](https://user-images.githubusercontent.com/1735744/39145637-6022ee9c-4702-11e8-92ac-a92b7e2cec29.png)
