### ISSUE TITLE
Cloud APIs: consider adding support for enabling APIs and service accounts for all JB IDEs

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/google-cloud-intellij#2182]
Working on #2148, it looks like most of Cloud APIs service account and API enablement code could quite easily ported to other IDEs since it's almost language and IDE agnostic. We can do this in a few steps:

* Extract Java related code and support, including Maven and BOM inspections, into a separate sub-module of `google-cloud-aps` module and make it dependent on `java`, removing `java` requirement from the core API module.
* Add extension points where necessary to extend core functionality with runtime specifics, like Java UI forms (BOM version and module selectors) and post-selection and post-enable actions (adding BOM and dependencies for Maven.)
* Implement extension point for adding service account environment variables into arbitrary runtime configurations with environment variables support - this is already being implemented as part of #2148.

If we do this, we can add very valuable functionality of dealing with enabling APIs, downloading JSON keys, and adding service account environment variables for all IDEs.

**Comment by etanshaul** [comment]
I agree this would be awesome.

The other thing is that currently all of the API enablement / service account management stuff is within the context of adding client libraries to the build. That's why, currently, we don't even allow this flow for Gradle users. So another change would be to decouple these somehow (so that we can get the API functionality for IDEs that do not yet have the language specific binding stuff).
