### ISSUE TITLE
Double "WEB-INF" directory created by Adding App Engine Standard Support

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/google-cloud-intellij#2223]
Project:
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/gaeinfo

Contains proper Web facet and App Engine configuration by default.
When you open this project, enable App Engine Facet by accepting prompt. Works with local server.

Steps after that:
1. Delete `webapp` completely.
2. Go to Cloud Tools -> Add App Engine Standard Support
3. Double directory is created.
<img width="367" alt="screen shot 2018-07-19 at 11 54 30 am" src="https://user-images.githubusercontent.com/11686100/42955425-a4435fe8-8b4b-11e8-909f-251b8b787e4e.png">

**Comment by etanshaul** [comment]
is this in UE?

**Comment by ivanporty** [comment]
UE 2018.1

**Comment by etanshaul** [comment]
just for completeness, mind testing this in CE too since it uses different generation logic?

**Comment by ivanporty** [comment]
Works fine for CE - seems to be some sort of web facet conflict in this case.

**Comment by etanshaul** [comment]
the problem essentially is that 2 webroots exist:
![image](https://user-images.githubusercontent.com/1735744/42960809-f1e83a7a-8b5a-11e8-9962-4d958c26e1a8.png)

Since none of the webroots map to physical folders (we deleted the webapp folder), the code is selecting the first webroot:

`../main/webapp/WEB-INF`

After selecting this webroot, the code makes the assumption that a `WEB-INF` folder needs to always be created (in this case however _it is_ the WEB-INF) folder.

The fix here is to either:
1) select from the available web-roots in a more intelligent way (I'm not sure if this is plausible)
or
2) with the selected webroot, only create the WEB-INF folder if the leaf directory isn't already a WEB-INF


nice find.

**Comment by etanshaul** [comment]
Here's a look at the project's web-roots from the UI:
![image](https://user-images.githubusercontent.com/1735744/42960986-7667176c-8b5b-11e8-8eac-df02b47f92d3.png)

We have access to the path relative to the deployment root (2nd column). So we should be able to get the deployment root path and create the WEB-INF in there
