### ISSUE TITLE
Test failures on Mac

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-intellij#324]
Running the usual tests (./gradlew test) on Mac, many fail although everything seems to be passing on Linux and Travis. There's probably a platform dependence somewhere we should root out

**Comment by etanshaul** [comment]
Might be related to #187 . I have a PR for this pending. 

For that PR specifically, the reason the unit test was failing on mac was essentially because of slower processing than on our Linux boxes: the test had a race condition (between the test execution thread and the ansyc call to the Swing UI thread) leading to unpredictable results. 

We may be able to close this once the PR is merged.
