### ISSUE TITLE
we should log errors during cloud repo import and checkout

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#793]
#736 demonstrates that interesting errors are not being logged for reporting.  We should see if there's a way to detect interesting (non-transient) errors in source repo checkout and upload and make sure we're logging them.

**Comment by etanshaul** [comment]
These errors are actually "transient" errors in that they are due to the user's git setup. I don't think we should be throwing IDE errors to force logging for these.

Also, for source repo checkout we did enhance the error message shown to the user in https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1175. For source repo upload the API doesn't give us any more detailed message for these failures.

Once we find a way to mitigate these auth issues from within the IDE this will be less of a concern. I'm closing for now, but feel free to reopen if you disagree.
