### ISSUE TITLE
Creating a new App Engine project using the IJ wizard for Java EE projects creates a broken dev appserver config

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#945]
Steps to reproduce:
1) file -> new project
2)  select 'Java Enterprise' in left margin panel
3) select Google App Engine in the right panel and click next.
4) observe that the local server run configuration has a red 'x' on it and fails when you run it.
5) observe that the local server is listed twice as a library in the module dependencies settings.

**Comment by patflynn** [comment]
Found while testing #916.  There's some screenshots on that PR that may be of help.

**Comment by joaoandremartins** [comment]
I think I know what is causing this, and it only affects Java Enterprise projects. Creating a Java project (with the GAE facet enabled) produces a correct run/debug config.

What's happening is that a template run/config is being created at a time we still don't have any artifact context.

https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/run/AppEngineServerConfigurationType.java#L49

Then, `setupFrameworkSupport()`, where we already have the artifact context, calls `setupRunConfiguration()`.
For reasons not completely clear to me, for a Java Enterprise project, the following line returns a list with the one template run/debug config created before, whereas for a normal Java project, that list is empty.

https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/facet/impl/AppEngineUltimateWebIntegration.java#L113

I don't know if the template should be being returned, judging from a few comments on the IJ SDK:
https://github.com/JetBrains/intellij-community/blob/4e2d1a2e48b7951bb4af70e772873f862cd0c4d7/platform/lang-impl/src/com/intellij/execution/impl/RunManagerImpl.java#L255
https://github.com/JetBrains/intellij-community/blob/4e2d1a2e48b7951bb4af70e772873f862cd0c4d7/platform/lang-impl/src/com/intellij/execution/impl/RunManagerImpl.java#L66

From there, if the list is empty (i.e., Java project), we correctly create a new run/debug config with the artifact set. If the list isn't empty (i.e., Java Enterprise), we don't do anything and the incomplete run/debug config stays there without any artifact.

The problem here is that I don't want to manually write the artifact to the existing template config, since `setupRunConfiguration()` is called from places other than `setupFrameworkSupport()` (e.g., from AppEngineFacetImporter). We could be writing an artifact to a run config that's not the template one.

---------

In the meantime, what we can do is to fix run/debug config when the UI editor is opened. The user will see a bad run config that will turn good without them having done nothing.
Either that, or not select any artifact by default, when we only have one to choose from, and make the user select the correct artifact and have made something to fix the config.
Both are very suboptimal user experience, but involve the least hacking..
The best solution would be for the template to not be returned on Java Enterprise projects, but I'll have to file a bug with the IJ team to make sure this is a bug on their side or not.

**Comment by patflynn** [comment]
It seems like there is another problem in that we're not displaying in the
run config editor what the problem is.   Normally if there are errors in
the run config the field causing it is highlighted and I think there
sometimes is even a message specifying what action needs to be taken to fix
it.

I'm fine with not pre-selecting the artifact for now as long as the user
has clear messaging on how to fix the run config.
