### ISSUE TITLE
Don't clear parameters when deployable changes on Deployment UI

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#987]
For example, changing from exploded war to a Maven artifact will reset the other selections, including project ID, version name, etc.

**Comment by etanshaul** [comment]
I don't think this is valid due to the way the dialog works - when changing a deployment source, a new instance of the dialog is created, therefore it makes sense that the other settings are reset.

Feel free to keep open though if you want to investigate a workaround.

**Comment by joaoandremartins** [comment]
If the run config is the same, it should be persisted somewhere, right?

In that case, it should be a matter of restoring the settings on resetEditorFrom(), as in https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/google-cloud-tools-plugin/ultimate/src/com/google/cloud/tools/intellij/appengine/server/instance/AppEngineRunConfigurationEditor.java#L111

I don't think that the current behaviour is ideal.

**Comment by etanshaul** [comment]
I'm not sure that its the same run config. If you look at AppEngineDeploymentRunConfigurationEditor#resetEditorFrom, it is actually resetting from the persisted configuration. The problem is that when changing deployment sources, a _new_instance of this class is create and I don't think (although lets confirm) that the reset method is called. 

I think the idea is that when changing deployment sources, the previously selected options are not valid anymore and need to be reselected because you have brand new deployable who's settings could be completely different.

**Comment by joaoandremartins** [comment]
Yep, the reset method isn't called when the deployable is changed.

Can't think of a good way to make this work, so will just close this.
